-- PR-K · Multi-tenant foundation · Mig 1 — tenants table + tenant_id on all 13 domain
-- tables + log tables. Serves RQ-K1/K4, D-a24; resolves B-01/B-03/B-06.
-- Backward-compatible: tenant_id DEFAULT 1 NOT NULL backfills Kameraad (tenant 1), so all
-- live single-tenant code keeps working. Additive + idempotent (IF NOT EXISTS everywhere).
-- Do NOT apply to prod: this migration is for an isolated Supabase branch review.

-- Tenants: the product spine. Kameraad = 1. ICP is config (RQ-K4).
CREATE TABLE IF NOT EXISTS public.tenants (
  id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug         text UNIQUE NOT NULL,
  name         text NOT NULL,
  host         text UNIQUE,                       -- D-a30 anon booking resolution
  is_active    boolean NOT NULL DEFAULT true,
  -- ICP config surface (RQ-K4): terminology map, thresholds, consent-basis labels,
  -- review platform, brand/voice, locales, sending identity — all data, not code.
  config       jsonb NOT NULL DEFAULT jsonb_build_object(
                 'terminology', jsonb_build_object('provider','barbier','service','dienst'),
                 'thresholds',  jsonb_build_object('rebooking_weeks',5,'lapsed_weeks',8,'dormant_weeks',16,
                                                   'freq_cap_week',1,'freq_cap_month',4),
                 'locales',     jsonb_build_array('nl','en','fr','es','le'),
                 'sender',      jsonb_build_object('tx_domain','mail.kameraadhaarsnijder.be',
                                                   'mkt_domain','news.kameraadhaarsnijder.be')),
  created_at   timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.tenants (id, slug, name, host)
VALUES (1,'kameraad','Kameraad Haarsnijder','kameraadhaarsnijder.be')
ON CONFLICT (id) DO NOTHING;
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
-- Public/anon may read only the id+host+config needed to resolve a booking; no secrets here.
DROP POLICY IF EXISTS tenant_public_read ON public.tenants;
CREATE POLICY tenant_public_read ON public.tenants FOR SELECT TO anon, authenticated USING (is_active);

-- resolve_tenant(host) for the anonymous booking path (D-a30). Definer, read-only.
-- FAILS CLOSED (critic B4): unknown/unmatched host → NULL, never a silent fall-through to 1.
-- book_appointment (093000) rejects a NULL tenant, so a mis-hosted anon call cannot land in Kameraad.
CREATE OR REPLACE FUNCTION public.resolve_tenant(p_host text)
RETURNS int LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','pg_temp'
AS $$ SELECT id FROM public.tenants WHERE host = p_host AND is_active; $$;   -- NULL if no match
GRANT EXECUTE ON FUNCTION public.resolve_tenant(text) TO anon, authenticated;

-- Add tenant_id to every domain + log table, backfill 1, NOT NULL, indexed.
-- Additive + DEFAULT 1 keeps all live code working (B-01).
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['barbers','services','barber_services','availability','blocked_slots',
                           'customers','appointments','email_log','settings','audit_log',
                           'admin_users','content','site_content','marketing_spend'] LOOP
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS tenant_id int NOT NULL DEFAULT 1 REFERENCES public.tenants(id)', t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON public.%I (tenant_id)', t||'_tenant_idx', t);
  END LOOP;
END $$;

-- B-03: customers unique per tenant, not globally. The old constraint was raw `email`; the new
-- index is on lower(email), so pre-check for case-variant duplicates BEFORE creating it (a build
-- that already dedupes on the app side; abort + report if any collision remains).
DO $$ DECLARE dupes int; BEGIN
  SELECT count(*) INTO dupes FROM (
    SELECT tenant_id, lower(email) e FROM public.customers GROUP BY 1,2 HAVING count(*) > 1) d;
  IF dupes > 0 THEN RAISE EXCEPTION 'case-variant email dupes present (%): dedupe before the unique index', dupes; END IF;
END $$;
ALTER TABLE public.customers DROP CONSTRAINT IF EXISTS customers_email_key;
CREATE UNIQUE INDEX IF NOT EXISTS customers_tenant_email_key ON public.customers (tenant_id, lower(email));

-- B-06: per-tenant synthetic walk-in is tagged, not a magic UUID.
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS is_synthetic boolean NOT NULL DEFAULT false;
UPDATE public.customers SET is_synthetic = true WHERE id = '00000000-0000-0000-0000-0000000000d0';

-- DOWN (single-tenant only — do NOT run once tenant >1 exists):
--   DROP INDEX IF EXISTS public.customers_tenant_email_key;
--   ALTER TABLE public.customers ADD CONSTRAINT customers_email_key UNIQUE (email);
--   (then drop tenant_id columns / is_synthetic / resolve_tenant / tenants)
