-- PR-K · Mig 6 — Art. 28 sub-processor register (published change-notice surface).
-- Serves RQ-K7, D-a26. New table ships ENABLE ROW LEVEL SECURITY (critic B1); anon read is
-- limited to active rows (the published register), no anon/authenticated write.
-- Do NOT apply to prod: for an isolated Supabase branch review only.

CREATE TABLE IF NOT EXISTS public.sub_processors (
  id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,           -- Mailjet by Sinch, Mistral, Supabase, Meta, Google …
  purpose      text NOT NULL,           -- email delivery, LLM, hosting, social, reviews
  location     text NOT NULL,           -- FR / DE+BE / eu-central-1 / US (DPF)
  legal_basis  text NOT NULL,           -- EU-region DPA / DPF+SCC + consent
  dpa_url      text, is_active boolean NOT NULL DEFAULT true,
  added_at     timestamptz NOT NULL DEFAULT now(), retired_at timestamptz
);
ALTER TABLE public.sub_processors ENABLE ROW LEVEL SECURITY;
-- Published register (EDPB Opinion 22/2024 needs an active, readable change-notice surface).
DROP POLICY IF EXISTS subproc_public_read ON public.sub_processors;
CREATE POLICY subproc_public_read ON public.sub_processors FOR SELECT TO anon, authenticated USING (is_active);
INSERT INTO public.sub_processors (name,purpose,location,legal_basis,dpa_url) VALUES
 ('Mailjet by Sinch','Email delivery','Frankfurt DE + Saint-Ghislain BE','EU-region processing + DPA','https://www.mailjet.com/legal/dpa/'),
 ('Supabase','Hosting / Postgres / Auth / edge','eu-central-1','EU-region + DPA (US-parent DPF/SCC)','https://supabase.com/legal/dpa'),
 ('Mistral AI','LLM captions (Phase 2)','Paris FR','EU-region DPA, no training','https://mistral.ai/terms')
ON CONFLICT DO NOTHING;
